[workspace]
members = ["app"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
fern = "0.7.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
