[workspace]
members = ["app"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.10", features = ["derive"] }
log = "0.4.22"
fern = "0.6.2"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.39.1", features = ["full"] }
