[package]
name = "hyprvisor"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = "0.3.11"
serde = "1.0.188"
serde_json = "1.0.106"
