name: Deploy
on:
  push:
    branches:
      - 'release'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker container
        run: |
          docker pull archlinux:latest
          docker run --name arch-build -dit archlinux:latest
          docker exec arch-build pacman -Syu --noconfirm
          docker exec arch-build pacman -S --noconfirm base-devel dbus
      - name: Install toolchain in Docker
        run: |
          docker exec arch-build sh -c "curl https://sh.rustup.rs -sSf | sh -s -- -y"
          docker exec arch-build sh -c ". /root/.cargo/env && rustup default stable"
      - name: Build in Docker
        run: |
          docker cp . arch-build:/workspace
          docker exec arch-build sh -c ". /root/.cargo/env && cd /workspace && cargo build --release"
          docker cp arch-build:/workspace/target target
          docker cp arch-build:/workspace/systemd systemd
      - name: Build archive
        shell: bash
        run: |
          binary_name="hyprvisor"
          dirname="${binary_name}-${{ github.ref_name }}-x86_64-unknown-linux-gnu"
          mkdir -p "$dirname"
          mv "target/release/$binary_name" "$dirname/"
          mv "systemd/hyprvisor.service" "$dirname/"
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "RELEASE_PKG=$dirname.tar.gz" >> $GITHUB_ENV
      - name: Calculate SHA256 checksum
        shell: bash
        run: |
          sha256sum "$RELEASE_PKG" > "${RELEASE_PKG}.sha256"
          cat "${RELEASE_PKG}.sha256"
          echo "SHA256SUM=$(cat ${RELEASE_PKG}.sha256)" >> $GITHUB_ENV
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.RELEASE_PKG }}
            ${{ env.RELEASE_PKG }}.sha256
