name: Test Build
on:
  push:
    branches:
      - "testing/**"
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker container
        run: |
          docker pull archlinux:latest
          docker run --name arch-build -dit archlinux:latest
          docker exec arch-build pacman -Syu --noconfirm
          docker exec arch-build pacman -S --noconfirm base-devel libdbus
      - name: Install toolchain in Docker
        run: |
          docker exec arch-build sh -c "curl https://sh.rustup.rs -sSf | sh -s -- -y"
          docker exec arch-build sh -c ". /root/.cargo/env && rustup default stable"
      - name: Build in Docker
        run: |
          docker cp . arch-build:/workspace
          docker exec arch-build sh -c ". /root/.cargo/env && cd /workspace && cargo build --release --verbose"
          docker cp arch-build:/workspace/target target
      - name: Build archive
        shell: bash
        run: |
          binary_name="hyprvisor"
          dirname="${binary_name}-${{ github.ref_name }}-x86_64-unknown-linux-gnu"
          mkdir -p "$dirname"
          mv "target/release/$binary_name" "$dirname/"
          tar -czf "$dirname.tar.gz" "$dirname"
      - name: Calculate SHA256 checksum
        shell: bash
        run: |
          binary_name="hyprvisor"
          dirname="${binary_name}-${{ github.ref_name }}-x86_64-unknown-linux-gnu"
          sha256sum "$dirname.tar.gz" > "$dirname.tar.gz.sha256"
          cat "$dirname.tar.gz.sha256"
